### ISSUE TITLE
[Bug report] Major issue

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/reveraki#12]
Hey @codeblitz97 this is a critical error cause when u click on a watch now button of any anime we get a error called client side exeption error. i have attached the screenshot of the issue. 
i tried opening the website on 4-5 different devices i got the error on all those devices. after u reload the page the issue gets fixed.
![image](https://github.com/codeblitz97/reveraki/assets/131786207/d1a4786d-f30c-4c00-87c1-64c2255f8a0f)

can u fix this issue as soon as possible .
FYI: i tried VPNs and changing my ISP also but the same issue.

**Comment by sulvii** [comment]
I'm afraid but I'm unaware of this error

**Comment by sulvii** [comment]
I'm not sure why is that error is happening

**Comment by sulvii** [comment]
Update: It's not an issue with site, it is an issue with vercel, my vercel hobby tier reached it's limit so yeah

Use this: https://reveraki.netlify.app
