### ISSUE TITLE
[Suggestion] Anime cards on mobile devices. 

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/reveraki#13]
Hey @codeblitz97 i noticed that the anime cards on the mobile phone seems to be big. Which shows only 2 anime's in each category. I have added the screen shot below. Hope u can fix it soon. 
![Screenshot_2024-05-10-00-09-11-017_com android chrome](https://github.com/codeblitz97/reveraki/assets/131786207/4bb4d46b-6f5d-48a5-8266-64b5087f6b38)

**Comment by sulvii** [comment]
Yeah I saw that
