### ISSUE TITLE
(suggestions) adding catalog

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/reveraki#6]
Hi @codeblitz97 how about adding option to search anime by genre ,year ,type and release season.
like in the image below.
![image](https://github.com/codeblitz97/reveraki/assets/131786207/004689a6-b311-43bb-9c0b-9271b5e6d2bd)
hope to hear from u soon

**Comment by skgupta507** [comment]
can u maybe add anime tv and anime movie page seperately for the users conveniance.

**Comment by sulvii** [comment]
Done
