### ISSUE TITLE
(bug) Anime info not showing properly

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/reveraki#9]
hi @codeblitz97 the anime info on the watch page is not showing properly i think its misaligned with the player. Wanted to let you know so that u can fix it. Iam also adding the screenshot just in case.
![image](https://github.com/codeblitz97/reveraki/assets/131786207/243b5938-3613-49dd-a09a-6e5b2f8dcc61)

**Comment by sulvii** [comment]
Might as well just remove the description and truncate the title to one line and add link so when it is clicked it will redirect to `/info`
